In [1]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import folium
import pandas as pd
import geopandas
from geopandas import gpd

In [2]:
acc_gnr= pd.read_csv('https://opendata-ajuntament.barcelona.cat/data/dataset/87aa433e-fef8-4ff4-8f9a-d66e9beefff6/resource/c6b05180-8084-4d89-a80c-f56de1f8e4de/download/2018_accidents_persones_gu_bcn_.csv')
acc_gnr.head()

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Desc_Tipus_vehicle_implicat,Descripcio_sexe,Edat,Descripcio_tipus_persona,Descripcio_situacio,Descripcio_victimitzacio,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S000001,3,Sants-Montjuïc,11,el Poble-sec,273400,Paral·lel ...,117-119,Dilluns,Dl,...,Turisme,Home,41,Conductor,Presentat,Ferit lleu: Amb assistència sanitària en lloc ...,429910.63,4580909.28,2.160723,41.374806
1,2018S000001,3,Sants-Montjuïc,11,el Poble-sec,273400,Paral·lel ...,NaN,Dilluns,Dl,...,Turisme,Home,54,Conductor,Presentat,Ferit lleu: Amb assistència sanitària en lloc ...,429910.63,4580909.28,2.160723,41.374806
2,2018S000002,2,Eixample,9,la Nova Esquerra de l'Eixample,361406,Viladomat / Rosselló ...,NaN,Dilluns,Dl,...,Ciclomotor,Home,45,Conductor,Presentat,Ferit lleu: Hospitalització fins a 24h,428882.97,4582216.76,2.148281,41.386492
3,2018S000003,10,Sant Martí,64,el Camp de l'Arpa del Clot,161407,Indústria ...,252,Dilluns,Dl,...,Motocicleta,Home,70,Conductor,Presentat,Ferit lleu: Hospitalització fins a 24h,431447.19,4585099.12,2.178621,41.412675
4,2018S000005,8,Nou Barris,56,Vallbona,330606,C-17 (Barcelona) ...,K14,Dilluns,Dl,...,Turisme,Dona,33,Conductor,Presentat,Ferit lleu: Hospitalització fins a 24h,431568.59,4590758.85,2.179432,41.463661

In [18]:
acc_veh_18 = pd.read_csv('https://opendata-ajuntament.barcelona.cat/data/dataset/317e3743-fb79-4d2f-a128-5f12d2c9a55a/resource/6e2daeb5-e359-43ad-b0b5-7fdf438c8d6f/download/2018_accidents_vehicles_gu_bcn_.csv')
acc_veh_18

,Codi_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Descripcio_tipus_vehicle,Descripcio_model,Descripcio_marca,Descripcio_color,Descripcio_carnet,Antiguitat_carnet,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S007344,1,Ciutat Vella,1,el Raval,269108,Rambla ...,1,Diumenge,Dg,...,Turisme,CORDOBA,SEAT,Blanc,B,5,431228.30,4581110.84,2.176455,41.376735
1,2018S009617,1,Ciutat Vella,1,el Raval,701265,B-10 (Besòs) ...,K110,Dilluns,Dl,...,Turisme,206,PEUGEOT,Blau,B,1,431320.52,4580791.56,2.177594,41.373868
2,2018S008382,1,Ciutat Vella,2,el Barri Gòtic,34308,Ferran ...,2,Divendres,Dv,...,"Camió rígid > 3,5 tones",Desconegut,DAF-HERMANNS,Taronja,C,25,431052.34,4581514.69,2.174305,41.380358
3,2018S002684,1,Ciutat Vella,2,el Barri Gòtic,55909,Call ...,21,Dilluns,Dl,...,"Camió rígid > 3,5 tones",ML140E24 E,IVECO FIAT,Blanc,C,11,431241.33,4581757.56,2.176538,41.382561
4,2018S004886,1,Ciutat Vella,2,el Barri Gòtic,82901,Colom ...,25,Dimarts,Dm,...,Taxi,TOLEDO,SEAT,Negre/Groc,B,5,431390.44,4581135.49,2.178391,41.376971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19074,2018S006251,10,Sant Martí,73,la Verneda i la Pau,150852,Fernando de los Ríos ...,NaN,Dilluns,Dl,...,Turisme,VECTRA,OPEL,Platejat,Desconegut,Desconegut,433930.24,4586310.21,2.208196,41.423791
19075,2018S006492,10,Sant Martí,73,la Verneda i la Pau,153205,Guipúscoa ...,132,Diumenge,Dg,...,Turisme,307,PEUGEOT,Gris,B,1,433522.49,4585979.28,2.203353,41.420777
19076,2018S006492,10,Sant Martí,73,la Verneda i la Pau,153205,Guipúscoa ...,NaN,Diumenge,Dg,...,Turisme,C4,CITROEN,Negre,B,24,433522.49,4585979.28,2.203353,41.420777
19077,2018S006492,10,Sant Martí,73,la Verneda i la Pau,153205,Guipúscoa ...,NaN,Diumenge,Dg,...,Turisme,MINI COOPER,MINI,Desconegut,Desconegut,Desconegut,433522.49,4585979.28,2.203353,41.420777
19078,2018S009754,10,Sant Martí,73,la Verneda i la Pau,153205,Guipúscoa / Maresme ...,138,Dijous,Dj,...,Turisme,A4,AUDI,Vermell,B,29,433561.94,4586017.93,2.203821,41.421128

In [20]:
acc_veh_18.columns

Index(['Codi_expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri',
       'Nom_barri', 'Codi_carrer', 'Nom_carrer', 'Num_postal ',
       'Descripcio_dia_setmana', 'Dia_setmana', 'Descripcio_tipus_dia', 'Any',
       'Mes_any', 'Nom_mes', 'Dia_mes', 'Hora_dia', 'Descripcio_torn',
       'Descripcio_causa_vianant', 'Descripcio_tipus_vehicle',
       'Descripcio_model', 'Descripcio_marca', 'Descripcio_color',
       'Descripcio_carnet', 'Antiguitat_carnet', 'Coordenada_UTM_X',
       'Coordenada_UTM_Y', 'Longitud', 'Latitud'],
      dtype='object')

In [24]:
acc_veh_18.loc[~(acc_veh_18['Descripcio_dia_setmana']=='Diumenge')|(acc_veh_18['Descripcio_dia_setmana']=='Dissabte'),'Descripcio_tipus_dia']='Laboral'

In [27]:
acc_veh_18.Descripcio_tipus_dia.value_counts()

Laboral         15316
Finde semana     3763
Name: Descripcio_tipus_dia, dtype: int64

In [26]:
acc_veh_18.to_csv('accidentes_2018.csv')

In [4]:
acc_turismes = acc_veh_18.loc[acc_veh_18['Descripcio_tipus_vehicle']=='Turisme']

In [5]:
acc_turismes.Descripcio_marca.unique()

array(['SEAT', 'PEUGEOT', 'RENAULT', 'Desconegut', 'FORD', 'BMW',
       'A.U.D.I.', 'OPEL', 'KIA', 'VOLKSWAGEN', 'SKODA', 'MERCEDES',
       'LANCIA', 'AUDI', 'FIAT', 'TOYOTA', 'MAZDA', 'CITROEN', 'DAEWOO',
       'A U D I', 'DACIA', 'DODGE', 'NISSAN', 'HONDA', 'HYUNDAI', 'MINI',
       'ALFA ROMEO', 'LAND ROVER', 'SUZUKI', 'SMART', 'VOLVO', 'JEEP',
       'TATA', 'LEXUS', 'PORSCHE', 'MITSUBISHI', 'CHEVROLET', 'B.M.W.',
       'CHRYSLER', 'ES DESCONEIX', 'JAGUAR', 'SSANGYONG', 'SAAB',
       'SUBARU', 'INFINITI', 'IRISBUS', 'MERCEDES-BENZ', 'PIAGGIO',
       'JAGUAR LAND ROV', 'LEONART', 'B M W', 'MECEDES', 'ROVER',
       'IVECO FIAT', 'FERRARI', 'MASERATI', 'MERCEDES B', 'BERGADANA',
       'S.Y.M', 'APRILIA', 'IVECO BUS', 'KYMCO', 'LINCOLN', 'GALLOPER',
       'TECNUVE'], dtype=object)

In [11]:
acc_turismes.groupby('Descripcio_marca',as_index=False).sum()

,Descripcio_marca,Codi_districte,Codi_barri,Codi_carrer,Any,Mes_any,Dia_mes,Hora_dia,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,A U D I,201,1125,8551727,82738,254,582,620,1.762913e+07,1.879562e+08,88.607198,1697.618196
1,A.U.D.I.,103,578,4993406,42378,145,387,321,9.034161e+06,9.626225e+07,45.440126,869.440182
2,ALFA ROMEO,181,1048,12975591,70630,206,539,452,1.504867e+07,1.604345e+08,75.635071,1449.042823
3,APRILIA,2,6,89004,2018,6,26,17,4.317934e+05,4.584115e+06,2.182874,41.403837
4,AUDI,1911,10637,99004186,778948,2438,6366,5564,1.659433e+08,1.769324e+09,833.887476,15980.516694
...,...,...,...,...,...,...,...,...,...,...,...,...
60,TATA,2,9,100800,2018,1,8,1,4.290626e+05,4.581269e+06,2.150540,41.377974
61,TECNUVE,4,21,213806,2018,7,19,20,4.257822e+05,4.582778e+06,2.111129,41.391266
62,TOYOTA,1627,9174,76785830,643742,2147,4839,4202,1.372075e+08,1.462204e+09,689.958272,13206.620452
63,VOLKSWAGEN,3811,21307,222787116,1555878,4975,11994,10838,3.315109e+08,3.534109e+09,1666.257841,73253.669488
64,VOLVO,434,2366,25696844,191710,582,1712,1338,4.083722e+07,4.354592e+08,205.186049,3933.063254

In [14]:
acc_turismes.loc[acc_turismes['Descripcio_marca']=='A.U.D.I.', 'Descripcio_marca']='AUDI'
acc_turismes.loc[acc_turismes['Descripcio_marca']=='A U D I', 'Descripcio_marca']='AUDI'

In [15]:
acc_turismes.loc[acc_turismes['Descripcio_marca']=='B M W']='BMW'
acc_turismes.loc[acc_turismes['Descripcio_marca']=='B.M.W']='BMW'

c:\program files\python38\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-15-2ce24d81f1d2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_turismes.loc[acc_turismes['Descripcio_marca']=='B.M.W']='BMW'

In [7]:
acc_turismes.Descripcio_marca.unique

<bound method Series.unique of 0              SEAT
1           PEUGEOT
6           RENAULT
8        Desconegut
9              FORD
            ...
19074          OPEL
19075       PEUGEOT
19076       CITROEN
19077          MINI
19078          AUDI
Name: Descripcio_marca, Length: 7707, dtype: object>

In [8]:
acc_motos = acc_veh_18[acc_veh_18['Descripcio_tipus_vehicle']=='Moto']

In [10]:
acc_motos.Descripcio_marca.unique()

array([], dtype=object)